
# This is a basic workflow to help you get started with Actions

name: Get data and build trackers

# Controls when the workflow will run
on:
  schedule:
    # - cron: '40 12 * * 3'
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  render:
    name: Get and compile recent crimes data
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install gdal
        run: |
          brew install gdal
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("sf","zoo","pdftools","janitor","tidyverse","readxl","leaflet","leaflet.extras","leaflet.providers","htmlwidgets","htmltools","lubridate"))'
      - name: Get latest weekly crime data
        run: Rscript scripts/process_recent_durham_data.R
      - name: Process and compile crime data
        run: Rscript scripts/process_durham_crime.R
      - name: Render all markdowns from central script
        run: Rscript scripts/run_markdowns.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New crime data collected' || echo "No changes"
          git push origin || echo "No changes to commit"



